openapi: 3.2.0
info:
  title: LiteLLM Robots.txt API
  description: 'Enterprise Edition


    Proxy Server to call 100+ LLMs in the OpenAI format. **Customize Swagger Docs**


    👉 ```LiteLLM Admin Panel on /ui```. Create, Edit Keys with SSO. Having issues? Try ```Fallback Login```


    💸 ```LiteLLM Model Cost Map```.


    🔎 ```LiteLLM Model Hub```. See available models on the proxy. **Docs**'
  version: 1.95.0
tags:
- name: Robots.txt
paths:
  /robots.txt:
    get:
      summary: Get Robots
      description: 'Block all web crawlers from indexing the proxy server endpoints

        This is useful for ensuring that the API endpoints aren''t indexed by search engines'
      operationId: get_robots_robots_txt_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Robots.txt
components:
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      description: Bearer token
      in: header
      name: x-litellm-api-key
